theme = "custom"

[custom_theme]
base = "github-dark-default"
label = "T3 Dark"
background = "#0a0a0a"
panel = "#111111"
panelAlt = "#141414"
border = "#191919"
accent = "#568ef9"
accentMuted = "#343a47"
text = "#f5f5f5"
muted = "#a3a3a3"
addedSignColor = "#54c57a"
removedSignColor = "#ff6467"
selectedHunk = "#141414"
fileNew = "#54c57a"
fileDeleted = "#ff6467"
fileRenamed = "#51cec7"
fileModified = "#e4b750"
fileUntracked = "#87a7d0"
noteBorder = "#bb8aef"

[custom_theme.syntax]
keyword = "#568ef9"
string = "#54c57a"
comment = "#818181"
number = "#e4b750"
function = "#bb8aef"
type = "#51cec7"
operator = "#a3a3a3"
variable = "#f5f5f5"
