theme = "rose-pine"

[custom_theme]
base = "github-dark-default"
label = "Carbonfox"
background = "#161616"
panel = "#1c1c1c"
panelAlt = "#252525"
border = "#353535"
accent = "#78a9ff"
accentMuted = "#525253"
text = "#f2f4f8"
muted = "#7b7c7e"
addedSignColor = "#25be6a"
removedSignColor = "#ee5396"
selectedHunk = "#2a2a2a"
fileNew = "#25be6a"
fileDeleted = "#ee5396"
fileRenamed = "#3ddbd9"
fileModified = "#08bdba"
fileUntracked = "#33b1ff"
noteBorder = "#be95ff"

[custom_theme.syntax]
keyword = "#be95ff"
string = "#25be6a"
comment = "#7b7c7e"
number = "#3ddbd9"
function = "#78a9ff"
type = "#08bdba"
operator = "#33b1ff"
variable = "#dfdfe0"
