export PATH="$HOME/.node_modules/bin:$PATH"
export PATH="/usr/local/node/bin:$PATH"
export PATH="$HOME/.local/share/flutter/bin:$PATH"
# export PATH="$HOME/.local/share/miniconda3/bin:$PATH"
export ANDROID_HOME="$HOME/Android/Sdk"
export PATH="$ANDROID_HOME/platform-tools:$PATH"
export PATH="$HOME/.config/composer/vendor/laravel/installer/bin:$PATH"

export EDITOR="nvim"
export NVIM_APPNAME="lazyvim"
. "$HOME/.cargo/env"
